const translations = {
    ko: {
        "reservation-btn": "비회원 예약",
        "about-link": "호텔 소개",
        "rooms-link": "객실",
        "facilities-link": "편의 시설",
        "contact-link": "연락처",
        "attractions-link": "주변 관광",
        "developer-link": "사이트 개발자",
        "hotel-name": "임페리얼 사이공 한인호텔",
        "hotel-description": "호치민시 한인 타운(푸미흥)에 위치한 한국인이 직접 운영하는 임페리얼 사이공 호텔입니다.",
        "features-convenience": "관리와 편의",
        "hotel-area-description": "푸미흥은 동남아시아에서 가장 큰 한국 국외 거주민 지역이며, 치안상태가 안전하고 청결한 곳입니다. 다양한 한국 식당들과 편의시설들이 있으며, 인근에 SECC(베트남 국제 전시장), 크레센트몰, 비보시티같은 대형 쇼핑몰이 있습니다. 임페리얼 사이공 호텔은 이 지역 호텔 중 유일한 3성급 한인 호텔이며, 가장 규모가 큽니다. 골프부킹, 차량 서비스 및 골프채 임대 서비스를 합니다. ",
        "features-owner": "한국인 사장이 직접 관리",
        "features-breakfast": "매일 한식 조식뷔페 제공(오전 6시 - 10시)",
        "features-laundry": "무료 세탁 및 건조기 사용",
        "features-wifi": "호텔 전체 Wifi 설치",
        "features-tv": "실시간 한국 TV 시청 가능",
        "features-rooms": "객실과 시설",
        "features-bedding": "전객실 최고급 5성급 호텔에서 사용하는 메트리스 및 침구류 제공",
        "features-windows": "전객실 크고 넓은 창",
        "features-banquet": "1층 연회장",
        "features-terrace": "야외 테라스",
        "features-services": "서비스",
        "features-combined-services": "골프 부킹, 차량 서비스 및 골프채 임대 서비스",
        "features-tour": "주변 관광지 여행 서비스",
        "checkin-label": "체크인 날짜:",
        "checkout-label": "체크아웃 날짜:",
        "guests-label": "인원:",
        "submit-btn": "예약하기",
        "secret-code-label": "예약 확인을 위한 비밀 번호:",
        "check-reservation-title": "예약 확인",
        "email-check-label": "이메일:",
        "code-check-label": "비밀 번호:",
        "check-reservation-btn": "예약 확인하기",
        "contact-description": "호텔에 대한 문의 사항이 있으시면 언제든지 연락 주십시오.",
        "room-title": "객실 소개",
        "room-description": "총 51개의 객실이 있으며, 타 호텔에 비해 객실이 크고, 넓은 창을 갖추고 있습니다. 침대와 메트리스는 5성급 호텔의 침구류로 편안하고 아늑한 잠자리를 약속합니다. 각층마다 Wifi가 설치되어 있으며, 각 객실에는 에어컨, 한국 TV, 미니 바, 무료 생수, 냉장고, 안전 금고, 독서 등이 준비되어 있어 3성급 이상의 호텔 이상의 면모를 갖추고 있습니다. 또한, 스위트룸은 개별적인 테라스를 갖추고 있어 안락한 휴식을 제공합니다.",
        "suite-room": "럭셔리 스위트룸",
        "suite-room-description": "42m² (3실) - 개별 테라스 포함",
        "superior-room": "디럭스룸",
        "superior-room-description": "트윈 8, 싱글 35 (28m², 총 43실)",
        "standard-room": "스탠다드룸",
        "standard-room-description": "21m² (5실)",
        "facilities-title": "편의 시설",
        "banquet-hall-title": "연회장",
        "banquet-hall-description": "호텔 1층에 60명 이상이 한 공간에서 식사 및 음료를 나눌 수 있는 연회장이 있으며, 매일 아침 한식과 양식의 음식들이 뷔페식으로 투숙객들에게 제공됩니다. 점심 및 저녁은 한식 및 양식 등의 음식을 개별 주문 가능하며, 각종 모임 및 돌잔치, 회갑연 등의 각종 잔치 및 행사가 진행되는 공간입니다.",
        "meeting-room-title": "미팅룸",
        "meeting-room-description": "10명 이상이 독립된 공간에서 회의 및 간담회를 할 수 있는 장소입니다. PC, Fax, 복사기 등을 갖추고 있으며, 예약만 해주시면 언제든지 이용 가능합니다.",
        "terrace-title": "야외 테라스",
        "terrace-description": "20명 이상이 이용할 수 있도록 테이블과 의자가 배치된 조용하고 한적한 공간으로, 커피나 티를 즐길 수 있는 완벽한 장소입니다.",
        "suite-archive-title": "럭셔리 스위트룸 사진 아카이브",
        "suite-archive-description": "럭셔리 스위트룸의 다양한 모습을 확인해보세요. 각 사진은 객실의 고급스러운 분위기와 편안함을 보여줍니다.",
        "superior-archive-title": "수페리어룸 사진 아카이브",
        "superior-archive-description": "수페리어룸의 다양한 모습을 확인해보세요. 객실의 우아한 디자인과 편안함이 돋보입니다.",
        "standard-archive-title": "스탠다드룸 사진 아카이브",
        "standard-archive-description": "스탠다드룸의 다양한 모습을 확인해보세요. 경제적이면서도 편안한 숙박을 제공합니다.",
        // 야외 테라스
        "terrace-archive-title": "야외 테라스 사진 아카이브",
        "terrace-archive-description": "야외 테라스의 다양한 모습을 확인해보세요. 고요하고 아늑한 분위기를 제공합니다.",
        // 연회장
        "banquet-archive-title": "연회장 사진 아카이브",
        "banquet-archive-description": "연회장의 다양한 모습을 확인해보세요. 넓고 편안한 공간에서 다양한 행사를 열 수 있습니다.",
        "contact-title": "연락처",
        "phone-label": "현지 전화번호:",
        "phone-korea-label": "한국 전화번호:",
        "kakao-label": "카카오톡:",
        "email-label": "이메일:",
        "address-label": "주소:",
        "name-label": "이름:",
        "email-form-label": "이메일:",
        "message-label": "메시지:",
        "submit-contact-btn": "문의하기",
        "ai-response-title": "AI 응답",
        "direct-contact-btn": "사장님에게 직접 문의하기",
        "attractions-title": "주변 관광",
        "vivo-title": "비보시티 쇼핑몰",
        "vivo-description": "호치민의 최신 쇼핑, 식사 및 엔터테인먼트의 중심지입니다.",
        "cu-chi-title": "구찌 터널",
        "cu-chi-description": "베트남 전쟁 시기의 역사적인 전쟁 유적지입니다.",
        "can-gio-title": "껀저섬",
        "can-gio-description": "유네스코가 지정한 맹그로브 보호 지역으로 야생 동물을 탐험할 수 있는 곳입니다.",
        "mekong-tour-title": "메콩강 투어",
        "mekong-tour-description": "베트남의 전통적인 보트 투어와 열대 과일 농장을 경험하세요.",
        "mui-ne-title": "무이네 사막",
        "mui-ne-description": "베트남의 숨겨진 보석, 사막과 해변이 만나는 곳입니다.",
        "hcm-night-tour-title": "호치민시 야간 투어",
        "hcm-night-tour-description": "호치민의 역동적인 야경과 활기찬 야시장을 체험하세요."
    },
    en: {
        "reservation-btn": "Guest Reservation",
        "about-link": "About",
        "rooms-link": "Rooms",
        "facilities-link": "Facilities",
        "contact-link": "Contact",
        "attractions-link": "Attractions",
        "developer-link": "Site Developer",
        "hotel-name": "Imperial Saigon Hotel",
        "hotel-area-description": "Phu My Hung is the largest Korean expatriate community in Southeast Asia, known for its safety and cleanliness. It offers a variety of Korean restaurants and convenient facilities. Nearby, there are major shopping malls such as SECC (Saigon Exhibition and Convention Center), Crescent Mall, and VivoCity. The Imperial Saigon Hotel is the only 3-star Korean hotel in the area and the largest in size. The hotel provides golf booking, vehicle services, and golf club rental services.",
        "hotel-description": "Imperial Saigon Hotel is located in Phu My Hung, a Korean town in Ho Chi Minh City, and is directly operated by Koreans.",
        "features-convenience": "Management and Convenience",
        "features-owner": "Managed directly by Korean owner",
        "features-breakfast": "Daily Korean buffet breakfast (6 AM - 10 AM)",
        "features-laundry": "Free laundry and dryer use",
        "features-wifi": "Hotel-wide Wifi installation",
        "features-tv": "Real-time Korean TV viewing",
        "features-rooms": "Rooms and Facilities",
        "features-bedding": "Premium mattresses and bedding used in 5-star hotels",
        "features-windows": "Large and spacious windows in every room",
        "features-banquet": "1st-floor banquet hall",
        "features-terrace": "Outdoor terrace",
        "features-services": "Services",
        "features-combined-services": "Golf booking, vehicle services, and golf club rental",
        "features-tour": "Nearby tourist attraction services",
        "checkin-label": "Check-in Date:",
        "checkout-label": "Check-out Date:",
        "guests-label": "Guests:",
        "submit-btn": "Book Now",
        "secret-code-label": "Secret Code for Reservation Check:",
        "check-reservation-title": "Check Reservation",
        "email-check-label": "Email:",
        "code-check-label": "Secret Code:",
        "check-reservation-btn": "Check Reservation",
        "contact-description": "Please feel free to contact us with any inquiries about the hotel.",
        "room-title": "Room Information",
        "room-description": "The hotel offers a total of 51 rooms that are larger than those in other hotels and feature large windows. Beds and mattresses are from 5-star hotels, promising comfortable and cozy sleep. Each floor has Wi-Fi installed, and each room comes with air conditioning, Korean TV, a minibar, free bottled water, a refrigerator, a safe, and reading lights. The suite rooms also have private terraces for a relaxing stay.",
        "suite-room": "Luxury Suite Room",
        "suite-room-description": "42m² (3 rooms) - Includes private terrace",
        "superior-room": "Deluxe rooms",
        "superior-room-description": "Twin 8, Single 35 (28m², total 43 rooms)",
        "standard-room": "Standard Room",
        "standard-room-description": "21m² (5 rooms)",
        "facilities-title": "Facilities",
        "banquet-hall-title": "Banquet Hall",
        "banquet-hall-description": "The banquet hall on the first floor can accommodate more than 60 people for dining and drinks. Every morning, guests are offered a hearty buffet breakfast featuring both Korean and Western dishes. Lunch and dinner can be ordered individually, and the hall is perfect for various gatherings and celebrations such as birthday parties and anniversary events.",
        "meeting-room-title": "Meeting Room",
        "meeting-room-description": "A place where more than 10 people can hold meetings and discussions in a private space. Equipped with PC, fax, and copier, it is available anytime upon reservation.",
        "terrace-title": "Outdoor Terrace",
        "terrace-description": "A quiet and serene space equipped with tables and chairs for more than 20 people, making it the perfect place to enjoy coffee or tea.",
        "suite-archive-title": "Luxury Suite Room Photo Archive",
        "suite-archive-description": "Explore various views of the Luxury Suite Room. Each photo showcases the luxurious atmosphere and comfort of the room.",
        "superior-archive-title": "Superior Room Photo Archive",
        "superior-archive-description": "Explore the various views of the Superior Room. Its elegant design and comfort stand out.",
        "standard-archive-title": "Standard Room Photo Archive",
        "standard-archive-description": "Explore various views of the Standard Room, offering an economical yet comfortable stay.",
        // Outdoor Terrace
        "terrace-archive-title": "Outdoor Terrace Photo Archive",
        "terrace-archive-description": "Explore various views of the outdoor terrace, offering a serene and cozy atmosphere.",
        // Banquet Hall
        "banquet-archive-title": "Banquet Hall Photo Archive",
        "banquet-archive-description": "Discover various views of the banquet hall, perfect for hosting events in a spacious and comfortable environment.",
        "contact-title": "Contact Us",
        "phone-label": "Local Phone:",
        "phone-korea-label": "Korea Phone:",
        "kakao-label": "KakaoTalk:",
        "email-label": "Email:",
        "address-label": "Address:",
        "name-label": "Name:",
        "email-form-label": "Email:",
        "message-label": "Message:",
        "submit-contact-btn": "Submit Inquiry",
        "ai-response-title": "AI Response",
        "direct-contact-btn": "Contact the Owner Directly",
        "attractions-title": "Nearby Attractions",
        "vivo-title": "VivoCity Shopping Mall",
        "vivo-description": "The latest hub for shopping, dining, and entertainment in Ho Chi Minh City.",
        "cu-chi-title": "Cu Chi Tunnels",
        "cu-chi-description": "A historical war relic from the Vietnam War era.",
        "can-gio-title": "Can Gio Island",
        "can-gio-description": "A UNESCO-listed mangrove reserve for exploring wildlife.",
        "mekong-tour-title": "Mekong River Tour",
        "mekong-tour-description": "Experience traditional boat tours and tropical fruit farms in Vietnam.",
        "mui-ne-title": "Mui Ne Desert",
        "mui-ne-description": "A hidden gem where the desert meets the beach in Vietnam.",
        "hcm-night-tour-title": "Ho Chi Minh City Night Tour",
        "hcm-night-tour-description": "Experience Ho Chi Minh’s vibrant nightlife and bustling night markets."

    },
    vi: {
        "reservation-btn": "Đặt phòng khách",
        "about-link": "Giới thiệu",
        "rooms-link": "Phòng",
        "facilities-link": "Tiện nghi",
        "contact-link": "Liên hệ",
        "attractions-link": "Điểm tham quan",
        "developer-link": "Nhà phát triển trang web",
        "hotel-name": "Khách sạn Imperial Sài Gòn",
        "hotel-area-description": "Phú Mỹ Hưng là cộng đồng người Hàn Quốc lớn nhất tại Đông Nam Á, nổi tiếng với sự an toàn và sạch sẽ. Khu vực này có nhiều nhà hàng Hàn Quốc và các tiện ích thuận tiện. Gần đó có các trung tâm thương mại lớn như SECC (Trung tâm Triển lãm và Hội nghị Sài Gòn), Crescent Mall và VivoCity. Khách sạn Imperial Saigon là khách sạn Hàn Quốc 3 sao duy nhất trong khu vực và có quy mô lớn nhất. Khách sạn cung cấp dịch vụ đặt sân golf, dịch vụ xe và cho thuê gậy golf.",
        "hotel-description": "Khách sạn Imperial Sài Gòn tọa lạc tại Phú Mỹ Hưng, một khu phố Hàn Quốc tại Thành phố Hồ Chí Minh.",
        "features-convenience": "Quản lý và Tiện nghi",
        "features-owner": "Quản lý trực tiếp bởi chủ sở hữu người Hàn Quốc",
        "features-breakfast": "Bữa sáng buffet Hàn Quốc hàng ngày (6 giờ sáng - 10 giờ sáng)",
        "features-laundry": "Sử dụng miễn phí máy giặt và máy sấy",
        "features-wifi": "Cài đặt Wifi trong toàn bộ khách sạn",
        "features-tv": "Xem TV Hàn Quốc theo thời gian thực",
        "features-rooms": "Phòng và Tiện nghi",
        "features-bedding": "Nệm và bộ đồ giường cao cấp sử dụng tại các khách sạn 5 sao",
        "features-windows": "Cửa sổ lớn và rộng rãi trong mọi phòng",
        "features-banquet": "Hội trường tầng 1",
        "features-terrace": "Sân thượng ngoài trời",
        "features-services": "Dịch vụ",
        "features-combined-services": "Đặt sân golf, dịch vụ xe và cho thuê gậy golf",
        "features-tour": "Dịch vụ tham quan địa điểm du lịch",
        "checkin-label": "Ngày nhận phòng:",
        "checkout-label": "Ngày trả phòng:",
        "guests-label": "Số khách:",
        "submit-btn": "Đặt phòng ngay",
        "secret-code-label": "Mã bí mật để kiểm tra đặt phòng:",
        "check-reservation-title": "Kiểm tra đặt phòng",
        "email-check-label": "Email:",
        "code-check-label": "Mã bí mật:",
        "check-reservation-btn": "Kiểm tra đặt phòng",
        "contact-description": "Vui lòng liên hệ với chúng tôi nếu bạn có bất kỳ câu hỏi nào về khách sạn.",
        "room-title": "Giới thiệu phòng",
        "room-description": "Khách sạn cung cấp tổng cộng 51 phòng rộng hơn các khách sạn khác và có cửa sổ lớn. Giường và nệm đều từ các khách sạn 5 sao, đảm bảo giấc ngủ thoải mái và dễ chịu. Mỗi tầng đều được lắp đặt Wi-Fi, mỗi phòng đều có điều hòa, TV Hàn Quốc, minibar, nước đóng chai miễn phí, tủ lạnh, két sắt và đèn đọc sách. Các phòng suite cũng có sân thượng riêng để thư giãn.",
        "suite-room": "Phòng Suite Cao Cấp",
        "suite-room-description": "42m² (3 phòng) - Bao gồm sân thượng riêng",
        "superior-room": "Phòng Deluxe",
        "superior-room-description": "Giường đôi 8, giường đơn 35 (28m², tổng cộng 43 phòng)",
        "standard-room": "Phòng Tiêu Chuẩn",
        "standard-room-description": "21m² (5 phòng)",
        "facilities-title": "Tiện nghi",
        "banquet-hall-title": "Phòng Tiệc",
        "banquet-hall-description": "Phòng tiệc tại tầng 1 có thể chứa hơn 60 người dùng bữa và thưởng thức đồ uống. Mỗi sáng, khách được thưởng thức bữa sáng buffet thịnh soạn với các món ăn Hàn Quốc và phương Tây. Bữa trưa và bữa tối có thể được gọi riêng và phòng tiệc phù hợp cho các buổi họp mặt và sự kiện như tiệc sinh nhật và kỷ niệm.",
        "meeting-room-title": "Phòng Họp",
        "meeting-room-description": "Một nơi có thể tổ chức các cuộc họp và thảo luận riêng tư cho hơn 10 người. Được trang bị PC, máy fax và máy photocopy, phòng họp luôn sẵn sàng khi đặt trước.",
        "terrace-title": "Sân Thượng Ngoài Trời",
        "terrace-description": "Không gian yên tĩnh và thoáng đãng, được trang bị bàn ghế cho hơn 20 người, là nơi lý tưởng để thưởng thức cà phê hoặc trà.",
        "suite-archive-title": "Lưu trữ ảnh phòng Suite cao cấp",
        "suite-archive-description": "Khám phá các góc nhìn khác nhau của phòng Suite cao cấp. Mỗi bức ảnh thể hiện sự sang trọng và thoải mái của căn phòng.",
        "superior-archive-title": "Lưu trữ ảnh phòng Superior",
        "superior-archive-description": "Khám phá các góc nhìn khác nhau của phòng Superior. Thiết kế thanh lịch và sự thoải mái nổi bật.",
        "standard-archive-title": "Lưu trữ ảnh phòng Tiêu Chuẩn",
        "standard-archive-description": "Khám phá các góc nhìn khác nhau của phòng Tiêu Chuẩn, mang đến kỳ nghỉ thoải mái với chi phí hợp lý.",
        // Sân Thượng Ngoài Trời
        "terrace-archive-title": "Lưu trữ ảnh Sân Thượng",
        "terrace-archive-description": "Khám phá các góc nhìn khác nhau của sân thượng ngoài trời, mang lại không gian yên tĩnh và ấm cúng.",
        // Phòng Tiệc
        "banquet-archive-title": "Lưu trữ ảnh Phòng Tiệc",
        "banquet-archive-description": "Khám phá các góc nhìn khác nhau của phòng tiệc, phù hợp để tổ chức các sự kiện trong không gian rộng rãi và thoải mái.",
        "contact-title": "Liên hệ",
        "phone-label": "Số điện thoại địa phương:",
        "phone-korea-label": "Số điện thoại Hàn Quốc:",
        "kakao-label": "KakaoTalk:",
        "email-label": "Email:",
        "address-label": "Địa chỉ:",
        "name-label": "Tên:",
        "email-form-label": "Email:",
        "message-label": "Tin nhắn:",
        "submit-contact-btn": "Gửi yêu cầu",
        "ai-response-title": "Phản hồi từ AI",
        "direct-contact-btn": "Liên hệ trực tiếp với chủ khách sạn",
        "attractions-title": "Điểm Tham Quan Gần Đó",
        "vivo-title": "Trung Tâm Mua Sắm VivoCity",
        "vivo-description": "Trung tâm mua sắm, ăn uống và giải trí hiện đại nhất tại Thành phố Hồ Chí Minh.",
        "cu-chi-title": "Địa Đạo Củ Chi",
        "cu-chi-description": "Di tích chiến tranh lịch sử từ thời kỳ Chiến tranh Việt Nam.",
        "can-gio-title": "Đảo Cần Giờ",
        "can-gio-description": "Khu dự trữ sinh quyển ngập mặn được UNESCO công nhận để khám phá động vật hoang dã.",
        "mekong-tour-title": "Tour Sông Mê Kông",
        "mekong-tour-description": "Trải nghiệm du thuyền truyền thống và các trang trại trái cây nhiệt đới tại Việt Nam.",
        "mui-ne-title": "Sa Mạc Mũi Né",
        "mui-ne-description": "Viên ngọc ẩn nơi sa mạc và biển giao nhau tại Việt Nam.",
        "hcm-night-tour-title": "Tour Đêm Thành Phố Hồ Chí Minh",
        "hcm-night-tour-description": "Trải nghiệm cuộc sống về đêm sôi động và chợ đêm tại Thành phố Hồ Chí Minh."

    },
    ch: {
        "reservation-btn": "非会员预约",
        "about-link": "酒店介绍",
        "rooms-link": "客房",
        "facilities-link": "便利设施",
        "contact-link": "联系方式",
        "attractions-link": "周边旅游",
        "developer-link": "网站开发者",
        "hotel-name": "帝国西贡韩人酒店",
        "hotel-description": "位于胡志明市韩人区（富美兴），由韩国人直接运营的帝国西贡酒店。",
        "features-convenience": "管理与便利",
        "hotel-area-description": "富美兴是东南亚最大的韩国侨民社区，以安全和整洁著称。这里有各种韩国餐厅和便利设施。附近有 SECC（西贡国际展览中心）、新月广场和 VivoCity 等大型购物中心。帝国西贡酒店是该地区唯一的三星级韩资酒店，也是规模最大的。酒店提供高尔夫预订、车辆服务以及高尔夫球杆租赁服务。",
        "features-owner": "由韩国人老板直接管理",
        "features-breakfast": "每日提供韩式自助早餐（上午6点 - 10点）",
        "features-laundry": "免费洗衣和烘干机使用",
        "features-wifi": "酒店全覆盖Wifi",
        "features-tv": "可观看韩国电视直播",
        "features-rooms": "客房与设施",
        "features-bedding": "所有客房均配备五星级酒店同款床垫及寝具",
        "features-windows": "所有客房均设有大窗户",
        "features-banquet": "一楼宴会厅",
        "features-terrace": "户外露台",
        "features-services": "服务",
        "features-combined-services": "高尔夫预订、车辆服务及高尔夫球杆租赁",
        "features-tour": "周边旅游服务",
        "checkin-label": "入住日期:",
        "checkout-label": "退房日期:",
        "guests-label": "入住人数:",
        "submit-btn": "预约",
        "secret-code-label": "预订确认密码:",
        "check-reservation-title": "预订确认",
        "email-check-label": "电子邮箱:",
        "code-check-label": "密码:",
        "check-reservation-btn": "确认预订",
        "contact-description": "如有任何疑问，请随时联系我们。",
        "room-title": "客房介绍",
        "room-description": "酒店共设有51间客房，相较其他酒店，客房面积更大，并配备宽敞的窗户。床垫与寝具采用五星级酒店标准，提供舒适温馨的睡眠环境。每层均安装Wifi，每间客房配有空调、韩国电视、迷你吧、免费矿泉水、冰箱、保险柜和阅读灯，具备超越三星级酒店的优越条件。此外，豪华套房设有私人露台，提供安逸的休息空间。",
        "suite-room": "豪华套房",
        "suite-room-description": "42m²（3间） - 带独立露台",
        "superior-room": "豪华客房",
        "superior-room-description": "双床房8间，单床房35间（28m²，总计43间）",
        "standard-room": "标准客房",
        "standard-room-description": "21m²（5间）",
        "facilities-title": "便利设施",
        "banquet-hall-title": "宴会厅",
        "banquet-hall-description": "酒店一楼设有可容纳60人以上的宴会厅，提供韩式与西式自助早餐。午餐和晚餐可点单韩式或西式美食，同时也是举办聚会、满月宴、寿宴等活动的理想场所。",
        "meeting-room-title": "会议室",
        "meeting-room-description": "可供10人以上独立开会或讨论的空间，配备PC、传真机、复印机等设备，可预约使用。",
        "terrace-title": "户外露台",
        "terrace-description": "可容纳20人以上，配有桌椅的安静休闲空间，是享受咖啡或茶的完美场所。",
        "suite-archive-title": "豪华套房照片档案",
        "suite-archive-description": "查看豪华套房的不同角度，感受高端舒适的氛围。",
        "superior-archive-title": "高级客房照片档案",
        "superior-archive-description": "浏览高级客房的各种设计，体验优雅舒适的入住环境。",
        "standard-archive-title": "标准客房照片档案",
        "standard-archive-description": "查看标准客房的不同角度，提供经济实惠又舒适的住宿体验。",
        "terrace-archive-title": "户外露台照片档案",
        "terrace-archive-description": "欣赏户外露台的多种景观，感受宁静与舒适。",
        "banquet-archive-title": "宴会厅照片档案",
        "banquet-archive-description": "查看宴会厅的不同布置，适合举办各类活动。",
        "contact-title": "联系方式",
        "phone-label": "当地电话:",
        "phone-korea-label": "韩国电话:",
        "kakao-label": "KakaoTalk:",
        "email-label": "电子邮件:",
        "address-label": "地址:",
        "name-label": "姓名:",
        "email-form-label": "电子邮件:",
        "message-label": "留言:",
        "submit-contact-btn": "提交咨询",
        "ai-response-title": "AI回复",    
        "direct-contact-btn": "直接联系老板",
        "attractions-title": "周边旅游",
        "vivo-title": "VivoCity购物中心",
        "vivo-description": "胡志明市最新的购物、餐饮及娱乐中心。",
        "cu-chi-title": "古芝地道",
        "cu-chi-description": "越南战争时期的历史战争遗址。",
        "can-gio-title": "芹耶岛",
        "can-gio-description": "联合国教科文组织指定的红树林保护区，可探索野生动植物。",
        "mekong-tour-title": "湄公河游览",
        "mekong-tour-description": "体验越南传统游船及热带水果园。",
        "mui-ne-title": "美奈沙丘",
        "mui-ne-description": "越南的隐藏宝石，沙漠与海滩交汇之地。",
        "hcm-night-tour-title": "胡志明市夜游",
        "hcm-night-tour-description": "体验胡志明市的繁华夜景与热闹夜市。"
    }
};

// 언어 변경 함수
function changeLanguage(language) {
    const elementsToTranslate = document.querySelectorAll("[data-translate]");

    elementsToTranslate.forEach(element => {
        const key = element.getAttribute("data-translate");
        element.textContent = translations[language][key];
    });

    localStorage.setItem("language", language);  // 선택한 언어를 localStorage에 저장
}

// 페이지 로드 시 저장된 언어 적용
window.addEventListener("DOMContentLoaded", () => {
    const savedLanguage = localStorage.getItem("language") || "ko";  // 기본값은 한국어
    changeLanguage(savedLanguage);
    document.getElementById("language-select").value = savedLanguage;  // 드롭다운 선택된 언어 설정
});
